### ISSUE TITLE
Whatsapp Client is Stuck in infinite loop

### ISSUE THREAD

**Issue by tndprint123** [iddhi-sulakshana/tnd-system#1]
![image](https://github.com/user-attachments/assets/f46ebb5b-5a62-419d-9bbf-0d9a09858870)

**Comment by tndprint123** [comment]
backend-1   | [2474:2474:1127/051259.952745:ERROR:process_singleton_posix.cc(340)] Failed to create /usr/src/app/whatsapp_cache/session/SingletonLock: File exists (17)
backend-1   | [2474:2474:1127/051259.953958:ERROR:chrome_main_delegate.cc(559)] Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption.

**Comment by iddhi-sulakshana** [comment]
Fixed in the https://github.com/iddhi-sulakshana/tnd-system/releases/tag/alpine-1.0.12
